volumes:

  data-ravendb:


services:

  ravendb:
    image: particular/servicecontrol-ravendb:5.7
    env_file: .env
    volumes:
      - data-ravendb:/opt/RavenDB/Server/RavenData
    restart: unless-stopped

  error:
    depends_on:
      - ravendb
    image: particular/servicecontrol:5.7
    command:
     - "--setup-and-run"
    env_file: .env
    restart: unless-stopped

  monitoring:
    image: particular/servicecontrol-monitoring:5.7
    command:
     - "--setup-and-run"
    env_file: .env
    restart: unless-stopped

  audit:
    depends_on:
      - ravendb
    image: particular/servicecontrol-audit:5.7
    command:
     - "--setup-and-run"
    restart: unless-stopped
    env_file: .env

  pulse:
    depends_on:
      - error
      - monitoring
    image: particular/servicepulse:1.41
    labels:
      traefik.enable: true
      traefik.http.routers.whoami.rule: Host(`servicepulse.localhost`)
      traefik.http.routers.whoami.tls: true
      traefik.http.routers.whoami.entrypoints: websecure
      traefik.http.routers.whoami.middlewares: auth
      traefik.http.middlewares.auth.basicauth.users: test:$$2y$$12$$ci.4U63YX83CwkyUrjqxAucnmi2xXOIlEF6T/KdP9824f1Rf1iyNG
    env_file: .env

  traefik:
    image: traefik:v3.1
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock