volumes:

  data-ravendb:
  config-ravendb:
  data-sqlt:

services:

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'yourStrong(!)Password'
      MSSQL_SA_PASSWORD: 'yourStrong(!)Password'
      MSSQL_DB: 'nservicebus'
      MSSQL_USER: 'nservicebus'
      MSSQL_PASSWORD: 'yourStrong(!)Password'
    volumes:
      - data-sqlt:/var/opt/mssql
    ports:
      - 1433:1433

  ravendb:
    image: ${CR}particular/servicecontrol-ravendb:${SC_TAG}
    env_file: .env
    volumes:
      - data-ravendb:/var/lib/ravendb/data
      - config-ravendb:/var/lib/ravendb/config

  error:
    depends_on:
      - ravendb
      - mssql
    image: ${CR}particular/servicecontrol:${SC_TAG}
    command: --setup-and-run
    env_file: .env
    restart: unless-stopped

  monitoring:
    image: ${CR}particular/servicecontrol-monitoring:${SC_TAG}
    depends_on:
      - mssql
    command: --setup-and-run
    env_file: .env
    restart: unless-stopped

  audit:
    depends_on:
      - ravendb
      - mssql
    image: ${CR}particular/servicecontrol-audit:${SC_TAG}
    command: --setup-and-run
    restart: unless-stopped
    env_file: .env

  pulse:
    depends_on:
      - audit
      - error
      - monitoring
    image: ${CR}particular/servicepulse:${SP_TAG}
    env_file: .env
    ports:
    - 9090:9090